---
abstract: 'Catalyst plugin for session management via headers.'
author:
  - justnoxx
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Session-State-Header
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/justnoxx/p5-catalyst-plugin-session-state-header.git
version: '0.01'
